---
- name: "update_password | change password for {{ user }} with plain password defined"
  ansible.builtin.user:
    name: '{{ user }}'
    update_password: always
    password: "{{ pass | password_hash('sha512') }}"
  when:
    - password_type == 'plain'

- name: "update_password | change password for {{ user }} with encrypted password defined"
  ansible.builtin.user:
    name: '{{ user }}'
    update_password: always
    password: "{{ pass }}"
  when:
    - password_type == 'encrypted'
